name: 'Dad Joke Action'
description: 'Generates a dad joke'
outputs:
  joke: # Este nombre debe coincidir EXACTAMENTE con el de core.setOutput
    description: 'The generated dad joke'
runs:
  using: 'node20'
  main: 'dist/index.js'